apiVersion: v1
data:
  config: |
    ConfigRepo: ssh://git@github.com/weaveworks-gitops-test/test-app-liu1mjm9.git
    FluxNamespace: wego-system
    WegoNamespace: wego-system
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: weave-gitops-config
  namespace: wego-system
