apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-dyc9vm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dyc9vm
  namespace: my-nginx-dyc9vm
  labels:
    name: nginx-dyc9vm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-dyc9vm
  template:
    metadata:
      namespace: my-nginx-dyc9vm
      labels:
        name: nginx-dyc9vm
    spec:
      containers:
      - name: nginx-dyc9vm
        image: nginx
        ports:
        - containerPort: 80

